### ISSUE TITLE
Segmentation fault when it can't write the model

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#139]
You may have thought checking the directory was enough to protect against stupid users, but I can be more stupid!  

```bash
/mt/marian-dev/build/marian --train-sets /mt/data/corpus.tc.{lv,en} --vocabs /mt/data/vocab.{lv,en} --model /dev/cannot_write.npz --mini-batch-fit --disp-freq 10 --device 1 --after-batches 11
```
Produces this output:
```
[2017-11-20 16:40:57] Ep. 1 : Up. 10 : Sen. 550 : Cost 155.73 : Time 21.78s : 269.88 words/s
[2017-11-20 16:40:58] Training finished
[2017-11-20 16:40:58] Saving model to /dev/cannot_write.npz
Segmentation fault (core dumped)
```

**Comment by emjotde** [comment]
That's more like malicious :) 
Also, you do have commit access, you know?

**Comment by emjotde** [comment]
The fix actually throws sometimes even if it can write to the directory. Re-opening. If you need an example, it's happening for me on AWS.

**Comment by hieuhoang** [comment]
I'm getting this error:
  Error: /home/hieu/workspace/github/marian.master/src/marian/src/common/config_parser.cpp:168 in void marian::ConfigParser::validateOptions() const threw util::Exception because `!(boost::filesystem::status(modelDir).permissions() & boost::filesystem::owner_write)'.
No write permission in model directory

when I run:
   $amunmt/build/marian -t corpus.1.de.bpe corpus.1.en.bpe --valid-sets input.tc.1.bpe reference.tc.1.bpe --dim-vocabs 100 100 --early-stopping 10 --vocabs vocab.de vocab.en

Directory permission is fine, it ran ok a week ago

**Comment by emjotde** [comment]
Specify --model ./model.npz with "./" as a work-around. It throws if there is no folder at all in the path. Will take a look at it soon unless Roman fixes it first.

**Comment by emjotde** [comment]
Urgs. That's another one, now you need to specify the vocabulary path explicitly too: `--vocabs src.yml trg.yml`. It will be created there. Before it would just create them where the corpus was with `*.yml`. Not sure this is actually a bug. Maybe it's better to force the user to specify a path, just needs a better message.

**Comment by hieuhoang** [comment]
ok, this works
  $amunmt/build/marian -t corpus.1.de.bpe corpus.1.en.bpe --valid-sets input.tc.1.bpe reference.tc.1.bpe --dim-vocabs 100 100 --early-stopping 10  --vocabs $DIR/vocab.de.yml $DIR/vocab.en.yml --model $DIR/model.npz

**Comment by emjotde** [comment]
Will take a look at that tomorrow, probably needs a couple of regression tests.

**Comment by emjotde** [comment]
I believe I fixed most of the issues. If not feel free to re-open.
