### ISSUE TITLE
Plans for amun?

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian-dev#192]
In light of the impending Marian CPU version merge, is the plan to stop developing amun?

**Comment by hieuhoang** [comment]
Not until marian is as fast as amun on gpu.

**Comment by hieuhoang** [comment]
also, certain things are easier to do in amun, eg. add new model , new device (fpga), without having to think about training. This is subjective of course

**Comment by emjotde** [comment]
I would indeed keep it until we get Marian to 80-90% speed of Amun on the GPU. On the CPU, the pre-merge Intel version it is close or comparable. The original Intel code is still faster than my merge, there is some more work to be done. At the moment I would consider the CPU version an early alpha. 

As for the difficulty to add new devices, this is becoming less and less true. I needed three days to add CPU to Marian with the kernels Intel prepared and have done quite some work on backend separation. That's not quite done yet, but getting closer to be actually functional. It seems counterproductive to me to put as much energy into Amun as you, Hieu, are doing. The same energy put into making Marian faster or adding FPGA support would make much more sense.

**Comment by hieuhoang** [comment]
i agree with that. 

I had offered to do the batching in marian but can't really spend much time on it at the end of my project. Will look at it again at the start of the next project

**Comment by emjotde** [comment]
As a first item on a wishlist I would be interested in having this fused top-k softmax. That seems useful. I will work on getting lexical filtering done soon to be able to reduce the multiply in the output layer.

**Comment by hieuhoang** [comment]
i would go for the biggest reason for the the difference 1st - batching

**Comment by hieuhoang** [comment]
out of curioosity, do you have numbers for cpu v. gpu? Did intel do batching for cpu too?

**Comment by emjotde** [comment]
Behold the power of Marian. Because we ported (nearly) all operators batching just works. As does everything else, training, scoring etc. No numbers yet as these are not the final implementations.

**Comment by emjotde** [comment]
@kpu since you brought up the topic, what's your suggestion?

**Comment by kpu** [comment]
I support closing amun, taking care to preserve/port performance improvements and keep current users happy.  So there should be clear documentation (perhaps even a program) to turn amun arguments into compatible Marian arguments.  

I am willing to pay @hieuhoang to "look at it again at the start of the next project"

Different device support should become easier in Marian now that it has (or will have) CPU/GPU factored out.

**Comment by emjotde** [comment]
I was thinking for a while to create a dummy amun binary that is actually marian but has amun interface.

**Comment by hieuhoang** [comment]
I would agree that we should preserve Amun's performance, this is after all one of the raison d'etre of creating a toolkit with low-level CUDA.

I would hesitate in putting too much work into the port unless it's already close. The (stability) improvements to Amun took months of drudge even with a smaller codebase and where the code was already fast. It may be more that you actually realise, doing it as part of an already short academic project is risky. A piecemeal port would expose the shortcoming of the work which is not in anyone's interest. What's probably needed is a mini MosesCore/Moses2 project where it can be put to bed once and for all

Just having a look at Marian's Tensor class now, it would be good to bear these things in mind when the CPU/GPU merge is being done:
   1. OpenCL's memory is contained in an opaque cl_mem rather than a pointer like CPU/CUDA. The Tensor/MemoryPiece class is better off being a hierarchy with different classes for difference devices, rather than a 1 size fits all class.
  2. Reduced precision and using matrices of different precisions in the same model is one of the advantage of FPGA. It would be good for the Tensor class to be templated by type rather than hardcoded to float. Same goes for row/column major order
  3. There seems to be a lot of  this in the code
           if (GPU) 
              .....
          else 
              ... 
        Adding another device will be a pain

**Comment by emjotde** [comment]
Totally against doing another split like Moses2. This is the opposite of what be should be doing. 

1) Marian is currently going towards stronger compartmentalization, the backend is increasingly isolated from the translation/training part. My short-term goal is to not have any `if(GPU)...` outside the `src/tensor/` folder which will make it already more compact and manageable than `amun` ever was. I am maybe 4-5 files away from that goal. There is a bit left in `src/translator` and `src/training`. All models can already run on any backend. 

2) The argument that adding a new backend is a pain is moot. I did in three days. 

3) I am a big fan of dealing with problems when they arise and otherwise keep things running. That's the reason why I am putting the half-baked CPU version into master. It works, and pretty well at that. `Tensor.h` is actually pretty isolated already, changing underlying implementation should not be much of problem.

**Comment by emjotde** [comment]
Closing this for now as I am sanitizing the issues
