### ISSUE TITLE
Using Element() in Marian

### ISSUE THREAD

**Issue by afaji** [marian-nmt/marian-dev#203]
I wanted to know to what extend we can use Element() function in Marian.

I wanted to:
 1. Do absolute value over all tensor value, i.e Element(_1 = abs(_1), ...)
 2. Do conditional operation, i.e. something like Element(_1 = (_1 > _2)?_1:_2, ...)

Right now it can be implemented via cuda kernel functions, but I wonder if I can do it via the provided Element()

**Comment by emjotde** [comment]
Yes, but currently it's a bit complicated due to GPU/CPU code separation. Let's do the easy part first:

If you look into:
https://github.com/marian-nmt/marian-dev/blob/master/src/functional/predicates.h

You will see that both, `abs(x)` and a ternary operator in form of `if_then_else(condition, x, y)` exist, also we have `x > y` etc. So you can write:

```c++
Element(_1 = abs(_1), t);
Element(_1 = if_then_else(_1 > _2, _1, _2), t1, t2);
```

A few days ago that would have just worked (and still works for the CPU version). That was the easy part.

Now comes the hairy part. In order to make the *.cpp files not see CUDA-specific code I had to put the GPU version of Element(...) into an implementation file, it cannot be in a header:

https://github.com/marian-nmt/marian-dev/blob/master/src/tensors/gpu/element.cu

But it is a template with unknown type for the functor part and C++ cannot currently deal with that. So what will happen is, that your linker will fail after compiling everything with an error message like this:

```
undefined reference to `void marian::gpu::Element<marian::functional::Assign<marian::functional::Var<1>, marian::functional::UnaryFunctor<marian::functional::elem::Abs, marian::functional::Assignee<1> > >>(marian::functional::Assign<marian::functional::Var<1>, marian::functional::UnaryFunctor<marian::functional::elem::Abs, marian::functional::Assignee<1> > >, std::shared_ptr<marian::TensorBase>)'
```

The solution is to take the error message and put a declaration into 

https://github.com/marian-nmt/marian-dev/blob/master/src/tensors/gpu/element.inc

For `_1 = abs(_1)` this would look like this (after cleaning up namespaces):

```c++
template void Element<Assign<Var<1>, UnaryFunctor<elem::Abs, Assignee<1>>>>(Assign<Var<1>, UnaryFunctor<elem::Abs, Assignee<1>>>, marian::Tensor);
```

or (human readable version)

```c++
template void Element<decltype(_1 = abs(_1))>(decltype(_1 = abs(_1)), marian::Tensor);
```
I am using the less readable version because I can use regexes to turn the linker message into a declaration. In the future it might be worth to replace the default linker with a script that can handle this. 

Hello, code generation.

**Comment by emjotde** [comment]
@kpu, you should enjoy this :)

**Comment by kpu** [comment]
Explicit instantiation is very annoying to maintain for something general like Element.  Code generation would work though it's hacky.  Maybe this is a place for conditional compilation as a .cu if there's a GPU involved?

**Comment by emjotde** [comment]
That would mean maintaining nearly all files as cpp/cu copies or moving everything into headers.

**Comment by kpu** [comment]
mv && nvcc?

**Comment by kpu** [comment]
To be clear, I am opposed to a Hieu-style copy-everything approach.

**Comment by emjotde** [comment]
We also want to be able to use -DCOMPILE_CUDA=off which allows for a pure CPU version now. I believe the current way is least evil, though not perfect. Element(...) is a deeply hidden backend function and more of a tool for core developers.

**Comment by emjotde** [comment]
And moving into headers does not really solve the problem, it just delays it. For instance command/marian.cpp would then need to become a *.cu and we would need a *.cpp copy for the pure-cpu version.

**Comment by emjotde** [comment]
@hieuhoang 

https://github.com/marian-nmt/marian/tree/master/src/amun/gpu
https://github.com/marian-nmt/marian/tree/master/src/amun/cpu

:)

**Comment by hieuhoang** [comment]
haha, yer got me. To be fair, that was a merge of your cpu and gpu branches, which was an uber example of copy & paste. I reduced the duplication but didn't get rid of everything

**Comment by kpu** [comment]
@hieuhoang ls moses/Chart*

**Comment by hieuhoang** [comment]
oh alright. I way in a hurry. Sue me

**Comment by hieuhoang** [comment]
https://github.com/marian-nmt/marian/tree/cpu_stable/src
https://github.com/marian-nmt/marian/tree/gpu_multi_encoder/src

**Comment by emjotde** [comment]
No, that's what branches are for.

**Comment by afaji** [comment]
This does not work (segfault)
```
Element(_1 = if_then_else(abs(_1) <= cut_off, 0, _1), grads);
```

But this works
```
tmp->set(0);
Element(_1 = if_then_else(abs(_1) <= cut_off, _2, _1), grads, tmp);
```

cut_off is a float
grads and tmp are a Tensor

**Comment by emjotde** [comment]
The first one should not work. I'm rather surprised it even compiles.

**Comment by emjotde** [comment]
I suppose the 0 gets converted to a std::shared_ptr<TensorBase> null pointer. Hence the segfault.

**Comment by afaji** [comment]
Sorry I have to revive this, because it's not clear to me now.

Where I can put scalar, and where I'm not allowed to put scalar?

I can compare tensor with scalar, but cannot assign tensor with scalar with if_then_else?

I can assign tensor with scalar like `Element(_1 = 0, tmp);` for example.

**Comment by emjotde** [comment]
Oh wait, you are right, I misread that. That should work actually. Gimme a moment.

**Comment by emjotde** [comment]
Last commit should solve that. Infinite loops are bad.

**Comment by afaji** [comment]
thanks.. working fine now.
