### ISSUE TITLE
Add attention output

### ISSUE THREAD

**Issue by jorgtied** [marian-nmt/marian-dev#277]
It would be great to include an option to save attention weights when decoding or scoring.

**Comment by snukky** [comment]
Attention output is now obtainable by adding the `--alignment soft` option with marian-decoder or marian-scorer. I've briefly described the option here: https://marian-nmt.github.io/docs/#attention-output

**Comment by emjotde** [comment]
This currently works for RNN models only. We are working on getting this to work in a reasonable way with the transformer too. It's a bit more involved there.

**Comment by emjotde** [comment]
OK, we have it working for Transformer too. There is a couple of gotchas though. Since the transformer has by default 8*6 different target to source attention weight sets we choose by default the first head of the last decoder layer. You can either output attention weights or discretized alignments as described by @snukky.

There is a new feature now which allows to train the chosen attention head to be more similar to word alignment by providing moses-style word alignment during training with `--guided-alignment path/to/alignments`. The alignments need to correspond linewise to your training data.

**Comment by pmarcis** [comment]
@emjotde Hi! Do you have an example of what the `path/to/alignments` file has to contain? Is it word-level symmetrised fast-align output as in Moses? Or is it some word-part-based alignment?

**Comment by emjotde** [comment]
That’s exactly moses-format alignment.

0-0 1-1 … 

 If symmetrized or not is up to you. I am currently running a couple of ablative tests which layer is the best to use. Seems that using a head from the top layer shaves off about 0.2 BLEU, could also be we need to fade the guided_alignment cost slowly out (I think they did that in the original paper), will report back.

**Comment by pmarcis** [comment]
Thanks, for the clarification! 👍

**Comment by tomsbergmanis** [comment]
Hi @emjotde just to double check - the input is WORD alignment, as opposed to WORD-PART alignment? 
Thanks, 
Toms

**Comment by emjotde** [comment]
Alignment between whatever your token is.

**Comment by tomsbergmanis** [comment]
Cheers!

**Comment by snukky** [comment]
Outputting attention matrices and word alignment is in Marian for a while, and it has been described here: https://marian-nmt.github.io/docs/#attention-output. I'm closing the issue.
