### ISSUE TITLE
Unify way training costs are handled as ratio of cost sum and sample count

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#347]
Unify way training costs are handled as ratio of cost sum and sample count. The current way is over-complicated and makes things like average of averages happen etc. Also no-one actually uses all the different and partially wrong cost functions. The default (ce-mean) is actually wrong. 

FYI @frankseide

**Comment by frankseide** [comment]
But we must keep `ce-mean` because everyone else gets it wrong as well, and we should be able to implement those models.

**Comment by emjotde** [comment]
Wait... sarcasm?

**Comment by frankseide** [comment]
Nope, based on experience on developing CNTK. It's also rational: If you come from a tool that does it wrong, even if you know it, you would first want to replicate exactly the other tool, and only after that try to fix the configuration.

**Comment by emjotde** [comment]
hm... `--cost ce-sum (default) --norm-unit sentence (default word)`

**Comment by emjotde** [comment]
Or in other words, do you actually want to implement it, or just display it in a way as if was implemented as ce-mean.

**Comment by frankseide** [comment]
Implement it. With `ce-mean`, the total gradient gets divided by the number of sentences in the minibatch. Since typically the number of words is roughly equal across minibatches, words in minibatches with fewer long sentences (e.g. "B" in "A B C followed by 100 more words") get a larger gradient than otherwise identical words in minibatches with many short sentences (e.g. "B" in "A B C D" in a left-to-right LM). I don't know any NL scenarios where such arbitrary gradient weighting makes sense to me, which is why I consider `ce-mean` wrong as a concept. This is unrelated to the display question.

**Comment by emjotde** [comment]
Ratios are done. So closing this.
