### ISSUE TITLE
Scoring with --normalize does not work if the model uses a SentencePiece vocab

### ISSUE THREAD

**Issue by snukky** [marian-nmt/marian-dev#435]
For a model using SentencePiece vocabs, adding `--normalize` to a marian-scorer command generates the following error massage:

```
[2019-03-16 15:21:30] Error: Check me
[2019-03-16 15:21:30] Error: Aborted from marian::Ptr<marian::LabelwiseLoss> 
  marian::newLoss(marian::Ptr<marian::Options>, bool) in 
  /home/romang/marian/marian-dev/src/layers/loss.cpp:13
```

**Comment by ugermann** [comment]
Do we know which commit broke this? Seems to work in release 1.7.0.

**Comment by akbokha** [comment]
Had the same issue as @snukky , but it does indeed seem to work in release 1.7.0

Q: Is the instability of the `--normalize` option also the reason why this option is missing in the [marian-scorer options](https://marian-nmt.github.io/docs/cmd/marian-scorer/) documentation (it is present when executing the scorer with `--help`)

**Comment by frankseide** [comment]
I don't remember any way that the use of SentencePiece can have anything to do with this. A quick search on github only finds this line:
https://github.com/marian-nmt/marian-dev/blob/50d64de62cb3e47b912fdd3438ffacb566187263/src/layers/loss.cpp#L13
```
  if(costType == "ce-rescore") {
    return New<RescorerLoss>();
  } else if(costType == "ce-rescore-mean") {
    ABORT("Check me");
    return New<RescorerLoss>();
```
Are you using `ce-rescore-mean`? I remember that this check exists because there is indeed something not completely correctly implemented. Can you try `ce-rescore`?

**Comment by akbokha** [comment]
@frankseide Thank you for the swift reply and my apologies for the rather late reply. I should've been more specific when I said that "I had the same issue as @snukky". I was referring to the usage of the `--normalize` option to marian-scorer (and getting the same error).  

SentencePiece was not used for the model in my particular case, so you are most likely correct that this issue has nothing to do with SentencePiece. 

Anyway, I am not blocked by this issue in any way since the `normalize` option works fine in the 1.7.0 release. I just wanted to highlight that this issue still exists since the last comment in this thread was almost 3 months old / the issue has not been closed yet.

**Comment by emjotde** [comment]
Sorry for missing this issue. I fixed this recently when I ran into it myself. Closing.
