### ISSUE TITLE
finetune error

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian-dev#492]
i use marain-dev 1.6.0, i pretrain model in P40 multi-gpus, then i finetune in k80, if i build with : cmake .. && make -j40, then i start training, then i will encounter a error:
No batches to fetch, run prepare()
4446 Aborted from marian::data::BatchGenerator<DataSet>::BatchPtr marian::data::BatchGenerator<Dat     aSet>::next() [with DataSet = marian::data::CorpusBase; marian::data::BatchGenerator<DataSet>     ::BatchPtr = std::shared_ptr<marian::data::CorpusBatch>] in /marian-dev-1.6.     0/src/data/batch_generator.h: 184

if i use debug mode, then i can start training normal in k80, it's weird.

**Comment by emjotde** [comment]
hm, indeed. What exactly do you mean by debug mode?

**Comment by 520jefferson** [comment]
@emjotde 
debug model means, i build like this:
cmake -DCMAKE_BUILD_TYPE=Debug ..

**Comment by emjotde** [comment]
I cannot quite imagine how that would be connected to anything. Have you recompiled with Release and tried again?

**Comment by 520jefferson** [comment]
i rebuild with Release and it failed just now.

**Comment by emjotde** [comment]
I guess it's a bit late, but I just realized that the solution to this problems is to use `--no-restore-corpus`. This error happens when you continue training with a smaller corpus and it tries to restore the position according to its position in the old large corpus. It then runs out of batches and this happens. 

@snukky might be worth to add a better error message, something like and explanation what happened and that `--no-restore-corpus` can fix that if you changed corpora between resumed trainings.

**Comment by 520jefferson** [comment]
Thanks, I think you are right. 
By the way,  Can we use the 8-bit even 4-bit engine?

**Comment by emjotde** [comment]
8bit works, I am preparing a tutorial now. 4 bit is only a proof of concept, no computational advantages currently.

As for multi-lingual models I have no experience so far.

Closing this issue for now.
