### ISSUE TITLE
question about data weighting 

### ISSUE THREAD

**Issue by wingsyuan** [marian-nmt/marian-dev#573]
Hi.
 you mentioned in your document the sentence weighting strategy, each line of that file contains a real-value weight:

but I don't know the format of weights,  my weight files is as follow, smaller means more similar to sentences in certain domain :

-0.9
-0.8
...
0.0
0.1
0.2
...
1

Can you tell me how to set the format of weigths ? 
thanks very much!

**Comment by emjotde** [comment]
Hi, 
for sentence-weighting, one weight per corpus line is correct. However, the value range is important. Since this is multiplying the cost with the weight, you probably do not want negative weights (you would maximize cost then), rather values between 0 and X. There isn't really a maximum number, I usually use 0 to 1.
