### ISSUE TITLE
[Question] What is mini-batch, maxi-batch and mini-batch-fit?

### ISSUE THREAD

**Issue by sianvolta** [marian-nmt/marian-dev#757]
From the docs:

```
--mini-batch INT=64                   Size of mini-batch used during update
--mini-batch-words INT                Set mini-batch size based on words instead of sentences
--mini-batch-fit                      Determine mini-batch size automatically based on 
                                      sentence-length to fit reserved memory
--mini-batch-fit-step UINT=10         Step size for mini-batch-fit statistics

--maxi-batch INT=100                  Number of batches to preload for length-based sorting
--maxi-batch-sort TEXT=trg            Sorting strategy for maxi-batch: none, src, trg (not 
                                      available for decoder)
```

Is there a reference paper to the `mini-batch-fit` algorithm? Or can someone help point to the function(s) that's computing this? 

Is the mini-batch-fit dynamically calculated per maxi-batch? Or is it calculated only once before training, since the data is somehow sorted by `--maxi-batch-sort`?

**Comment by emjotde** [comment]
Hi,
did you read this part of the docs: https://marian-nmt.github.io/docs/#workspace-memory ?
The implementation is here: https://github.com/marian-nmt/marian-dev/blob/d5e773f937049d30a4a484b01c68c69f710f98b3/src/training/graph_group.cpp#L15

Essentially this is a binary search over different inputs sizes and batch sizes. Whenever an re-allocation exception is caught this gets recorded as hitting a memory limit, i.e. having found the maximal batch size per input size. Input size step size can be changed. 

Currently this happens in a special pre-computations step before training starts. It is implemented far less efficient than it could be, since it is executing a real forward/backward computation for each probing step. Ideally the would be simulated in the future. That would reduce the collection of batch size stats from a taking a minute or two to mere seconds.

**Comment by sianvolta** [comment]
Thank you for pointing to the documentation! That helps a lot.
