### ISSUE TITLE
Difference between ce-mean-words and ce-mean ?

### ISSUE THREAD

**Issue by GokulNC** [marian-nmt/marian-dev#789]
For the argument `--cost-type`, what is the difference between `ce-mean-words` and `ce-mean` ?

Assuming I am using Sentence Piece Tokenizer, does `word` here refer to whole words as in sentence?
Or the tokens after BPE?

Also, which loss type is recommended to use in which scenarios?

**Comment by frankseide** [comment]
`ce-mean-words` takes the average loss over all labels in the batch. If you use BPEs or word pieces as your representation, then that's what the average is taken over.

`ce-mean-words` is recommended. `ce-mean` takes the mean over the number of sentences in the batch, which leads to worse loss.

My personal preference is `ce-sum` which takes the sum over all labels, rather than the average. With `ce-sum`, each label contributes the same to the model, independent of fluctuations of the number of words in the batch, i.e. independent of the other sentences in the same batch; I feel that's a sane thing to expect. Note that the log will still report averages over tokens, so the numbers won't look much different than usual.

**Comment by GokulNC** [comment]
Thanks a lot, got it!

So basically,

|Loss|Explanation|
|----|-------|
|`ce-sum`|Sum of CE for all words (tokens)|
|`ce-mean-words`|Mean over all words in the batch|
|`ce-mean`|Mean over all sentences in the batch|
