### ISSUE TITLE
Logging to file seems to not work properly

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-dev#87]
After the recent changes it seems that logging to files is now buffered or not really working. Valid.log remains empty, train.log is missing entries (the config is not appearing in the log anymore which makes it hard to trace experiments). 

It also seems that previous entries are being removed, starting with a fresh file when a new training is started, this goes against the idea of using logs in my opinion. 

TBH, I would really prefer to freeze the way we use spdlog at some point. It is causing a lot more problems than it should.

**Comment by ugermann** [comment]
Do you have a setup (config file, data) that illustrates the problem? Preferably with old logs that show what should be in the logs.

**Comment by emjotde** [comment]
Will provide one. In the meantime just check that it seems only the "info" seems to go to the file, nothing else. --valid-log remains empty.

**Comment by ugermann** [comment]
Also, when was the last time things worked? (As in: which commit?)

**Comment by emjotde** [comment]
I'll take this over. Planning to change a couple of more things and then keep the version fixed.

**Comment by emjotde** [comment]
Reverted the submodule for now.

**Comment by ugermann** [comment]
Logging *is* complicated and different use cases justify different levels of logging. I'm arguing mostly from the point of view of a user who uses marian for translation. With marian and marian-train being merged eventually, a common approach to logging makes sense, methinks. 

When I use marian as / from a translation server, the only thing I want to see in the console is warnings, errors, and critical messages. When run within a pipeline on the command line, I may want to see more verbose output so that I can see if things are progressing. Being able to set log levels at run time makes sense to me. 

What's currently being achieved with a multitude of loggers, i.e.

```
Logger info{stderrLogger("info", "[%Y-%m-%d %T] %v", generalLogs)};
Logger warn{stderrLogger("warn", "[%Y-%m-%d %T] [warn] %v", generalLogs)};
Logger config{stderrLogger("config", "[%Y-%m-%d %T] [config] %v", generalLogs)};
Logger memory{stderrLogger("memory", "[%Y-%m-%d %T] [memory] %v", generalLogs)};
Logger data{stderrLogger("data", "[%Y-%m-%d %T] [data] %v", generalLogs)};
Logger valid{stderrLogger("valid", "[%Y-%m-%d %T] [valid] %v", validLogs)};
Logger translate{stderrLogger("translate", "%v")};
Logger devnull{stderrLogger("devnull", "%v")};
devnull->set_level(spdlog::level::off);
```

Can also be achieved with custom formatting (https://github.com/gabime/spdlog/wiki/3.-Custom-formatting) in one logger and using the right log level for the message, i.e.,

```
some_logger->info()
some_logger->warn()
```

etc. There are format specifiers to include logger name and log level in the log message.

In my opinion it makes sense to distinguish e.g., the following log destinations:

- console (i.e. stderr), which can be verbose when run from the command line interactively and terse when wrapped in a server
- a general log file for logging training / translation progress
- valid_out for validation output
- valid_log for validation-related log messages 

It would be worthwhile considering providing a file name pattern instead of the file name for the valid_* files, so that each run can generate a separate set of files; we may want to keep them around for analysis later on.

My suggestion would be to define global functions 

```
trace(args,...)
debug(args, ...)
info(args, ....)
warn(args, ...)
error(args, ...)
critical(args,...)

that each call 

console->{trace|debug|info|warn|error|critical}(args, ...);
logfile->{trace|debug|info|warn|error|critical}(args, ...);

and leave it up to these loggers' log level to output the message or not. 

I'm not even sure if we need a special log file for validation.

My main concern is though that I don't want too much clutter in the logging in production. At the very least, each log message should provide enough standardized information so that I can filter the output. When things are run under docker compose, ALL output is written to file, so when we're translating 10 live streams 24/7, as we are currently doing in SUMMA, that clutter piles up.

**Comment by ugermann** [comment]
Marcin, can you still provide a toy setup where things failed? I'm curious why this didn't work.

**Comment by emjotde** [comment]
I will, just not before Thursday, I will be travelling the whole day tomorrow. From what I saw the file management seems to be not working properly. It did write out the validation log in the end, but completely out of order as if the file pointers were out of whack.

**Comment by ugermann** [comment]
No rush, I've got plenty of stuff to keep myself busy with.
